### ISSUE TITLE
fetlife-ios > ios

### ISSUE THREAD

**Issue by Daddy** [fetlife/ios#31]
Following the same changes that happened recently with the Android branch, this should be renamed to "ios" or "iOS" for consistency.

**Comment by JohnBaku** [comment]
Should is a strong word... I think it would be nice personally.

For people's reference, this is the discussion that @Daddy was referring to:
https://github.com/fetlife/android/issues/102

**Comment by reneklacan** [comment]
👍

**Comment by Daddy** [comment]
Before any changes, what is the consensus on the new name; iOS or ios? 
@JohnBaku  @reneklacan

**Comment by reneklacan** [comment]
I am for all lowercase `ios` to keep all repo names consistent

**Comment by AliseEverly** [comment]
Agree on lowercase `ios`.

**Comment by alias1** [comment]
Lowercase seems the best choice all things considered.

**Comment by JohnBaku** [comment]
@jacortinas can we change repo name without changing anything to the code?

**Comment by AliseEverly** [comment]
@johnbaku From a building standpoint I don't see an issue as the repo has nothing to do with the structure of the files inside the repo.

**Comment by jacortinas** [comment]
@JohnBaku We can change the name of the repo without changing anything else.

**Comment by reneklacan** [comment]
I see that repo was already renamed, let's close this issue

**Comment by JohnBaku** [comment]
@reneklacan BOOM! Thanks playa!
