### ISSUE TITLE
Permission denied on Git Clone request

### ISSUE THREAD

**Issue by aschwab9009** [fetlife/ios#40]
### Steps to reproduce

I use terminal to enter the steps when I go to enter "git clone git@github.com:fetlife/ios.git" I get an error saying:

Cloning into 'ios'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Device Info

Tested on [device], iOS [version]

**Comment by alias1** [comment]
This is unrelated to this project. That clone method works using SSH. You need to add your SSH key to GitHub to clone it in that way.

An alternative way would be to clone using the https URL that GitHub provides.

**Comment by reneklacan** [comment]
Exactly like @alias1 said. Use `git clone https://github.com/fetlife/ios.git` instead if you don't have your SSH in Github or if you don't know how to do it. 

More info on adding SSH key to your github profile https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
