### ISSUE TITLE
No installation instructions for windows.

### ISSUE THREAD

**Issue by NTDLS** [fetlife/ios#52]
### Steps to reproduce
View readme.

### Expected behavior
Find instructions for installing on iOS from Windows.

### Actual behavior
Only found instructions for installing from Mac.

### Device Info
iPhone 8 and Windows 10.

**Comment by NTDLS** [comment]
Damn, I'm hilarious.

**Comment by kb1ibt** [comment]
The simple answer is, without Xcode (which is only released for macOS) you can't deploy the code to test on your device.

The more complex answer is something like options 1 through 8 from this link https://codewithchris.com/xcode-for-windows/
The reason I am excluding 9-12 is those won't work with the already existing code in this project.

**Comment by TheRojam** [comment]
Just a small hint... macOS and iOS share the same kernel and why in this world should apple do this? let ppl deploy ios apps via windows?
