### ISSUE TITLE
Compling error

### ISSUE THREAD

**Issue by kirigamikinbaku** [fetlife/ios#56]
### Steps to reproduce
Follow the instructions on  xcode 9.4.1 and os high sierra

### Expected behavior
be able tu run

### Actual behavior
Get several compiling error for dynamiBlurView and dateTools

### Device Info
iphone 6 and macbookpro

**Comment by whitehat007** [comment]
Please include the actual error messages that you are getting in order for us to help you.

That being said, I think I know what issue(s) you're getting for the DynamicBlurView pod. If the errors say something about being unable to access variables due to protection levels, then you will need to find where the variables that it refers to are defined (for example, `private var edgeRadius: Int = 1` or `fileprivate var filterType....`) and delete the words `private` or `fileprivate`. You should be able to compile the project then.

**Comment by kirigamikinbaku** [comment]
Thankyou!
most errors are now fixed. There is just another one I don't understand:

Cannot invoke 'draw' with an argument list of type '(UIImage, blurRadius: CGFloat, fixes: Bool, baseLayer: CALayer)'

here follows the full log

FetLife Workspace Group
Swift Conversion Group
Conversion to Swift 4 is available
Pods project Group
Validate Project Settings Group
/Users/pfphoto/ios/ios/Pods/Pods.xcodeproj Update to recommended settings
DynamicBlurView Group
Swift Compiler Error Group
/Users/pfphoto/ios/ios/Pods/DynamicBlurView/DynamicBlurView/DynamicBlurView.swift:157:13: Cannot invoke 'draw' with an argument list of type '(UIImage, blurRadius: CGFloat, fixes: Bool, baseLayer: CALayer)'
/Users/pfphoto/ios/ios/Pods/DynamicBlurView/DynamicBlurView/DynamicBlurView.swift:157:13: Overloads for 'draw' exist with these partially matching parameter lists: (CALayer, in: CGContext), (CGRect, for: UIViewPrintFormatter), (CGRect)
DateTools Group
Semantic Issue Group
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/DTTimePeriodChain.m:149:89: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
Documentation Issue Group
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:78:12: Parameter 'NSDate' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:78:12: Did you mean 'date'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:90:12: Parameter 'NSDate' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:90:12: Did you mean 'date'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:829:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:829:12: Did you mean 'months'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:844:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:844:12: Did you mean 'weeks'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:859:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:859:12: Did you mean 'days'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:874:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:874:12: Did you mean 'hours'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:889:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:889:12: Did you mean 'minutes'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:904:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:904:12: Did you mean 'seconds'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:935:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:935:12: Did you mean 'months'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:950:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:950:12: Did you mean 'weeks'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:965:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:965:12: Did you mean 'days'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:980:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:980:12: Did you mean 'hours'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:995:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:995:12: Did you mean 'minutes'?
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:1010:12: Parameter 'years' not found in the function declaration
/Users/pfphoto/ios/ios/Pods/DateTools/DateTools/NSDate+DateTools.m:1010:12: Did you mean 'seconds'?
Freddy Group
Swift Compiler Warning Group
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONEncodingDetector.swift:59:42: 'RandomAccessSlice' is deprecated: renamed to 'Slice'
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONEncodingDetector.swift:59:42: Use 'Slice' instead
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONEncodingDetector.swift:85:52: 'RandomAccessSlice' is deprecated: renamed to 'Slice'
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONEncodingDetector.swift:85:52: Use 'Slice' instead
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONDecodable.swift:60:43: 'characters' is deprecated: Please use String or Substring directly
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONDecodable.swift:61:27: 'init' is deprecated: Please use String or Substring directly
/Users/pfphoto/ios/ios/Pods/Freddy/Sources/JSONDecodable.swift:61:41: 'characters' is deprecated: Please use String or Substring directly

**Comment by whitehat007** [comment]
Ok, for that error try adding `self.` before the `draw` function call on line 157. It should now read `self.draw(...`. Hopefully that will work.

**Comment by kirigamikinbaku** [comment]
self.draw still gives 
/Users/pfphoto/ios/Pods/DynamicBlurView/DynamicBlurView/DynamicBlurView.swift:157:18: Cannot invoke 'draw' with an argument list of type '(UIImage, blurRadius: CGFloat, fixes: Bool, baseLayer: CALayer)'

/Users/pfphoto/ios/Pods/DynamicBlurView/DynamicBlurView/DynamicBlurView.swift:157:18: Overloads for 'draw' exist with these partially matching parameter lists: (CALayer, in: CGContext), (CGRect, for: UIViewPrintFormatter), (CGRect)

Any clue how I could proceed?

also: self is highlighted; .draw is not

Thankyou for being so supportive with a newbie :)

**Comment by whitehat007** [comment]
Try replacing the file with this one:
[DynamicBlurView.swift.zip](https://github.com/fetlife/ios/files/2320936/DynamicBlurView.swift.zip)
I know this one works so hopefully it'll solve the problem.

**Comment by kirigamikinbaku** [comment]
the code is smooth, I have to solve some other settings now:


Code Signing Error Group
Cannot create a iOS App Development provisioning profile for "asedfedekiri". Your development team, "Kirigami Kinbaku", does not support the Push Notifications capability.
No profiles for 'asedfedekiri' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'asedfedekiri'.
Code signing is required for product type 'Application' in SDK 'iOS 11.4'


I'll keep you posted

**Comment by ClioCJS** [comment]
could we please put the app on one of the alt app stores that isn't run by
apple? Then people who don't have an actual Mac computer can install it...

**Comment by kirigamikinbaku** [comment]
signing issues are now solved.

I get


Shell Script Invocation Error Group
Command /bin/sh failed with exit code 1

and the build fails

**Comment by kirigamikinbaku** [comment]
it works now :D

**Comment by ClioCJS** [comment]
Oh wow, I didn't know you could do that?! I thought it had to be unzipped
and modified to have my device id (tried & failed doing that once, spent
like 30min haha).  I take it you mean to plug my iPad into my Windows and
run iTunes and iTunes will let me install it that way?  THAT. IS. AWESOME.
:) :) !!!!!!!!!!!! <3 <3

**Comment by whitehat007** [comment]
@ClioCJS You'll still have to unzip it first lol but the .ipa file is all you need. If you run into problems using it on your iPad, please message me [here](https://fetlife.com/conversations/new?with=8647349). I haven't done much (read: any :P) testing on iPad and could really use some feedback.

**Comment by whitehat007** [comment]
Did you drag the file before connecting the device?

**Comment by ClioCJS** [comment]
Yup :) Even tried on 2 different PCs.

**Comment by ClioCJS** [comment]
Only thing i can think of is to downgrade to an even lower version of
iTunes...... but the one i hvae is still one before they removed the 'apps'
tab, so... I feel like that would probably be fruitless.

**Comment by adityasrini** [comment]
@whitehat007 Can I make a pull request against this repo with the included fixes? I got the same issues as @kirigamikinbaku and was also deploying to a 11.4 target. I have an iPhone 7. Also thought of updating the README.MD to require XCode 10 because the build fails otherwise with `Double` not having a `random` member.

**Comment by whitehat007** [comment]
@adityasrini In general, absolutely you can make your own pull request :) However, I already have a few PRs lined up with a bunch of bug fixes (including the `Double.random` error). What other fixes are you looking to add?

**Comment by ClioCJS** [comment]
I don't know if it's jailbroken. I tried awhile back, but I couldn't really
verify. And got swindled out of $10 along the way. Somehow I have no
problem rooting every different android device I've owned. But my iPad is
the fastest :D

**Comment by whitehat007** [comment]
Well if you have the Cydia app then it’s most likely jailbroken. What tool did you use?

**Comment by adityasrini** [comment]
@whitehat007 the `Double.random` is actually not an error and a documented Swift API. It just needs an Xcode 10 beta to be recognized and work. However if there’s a fix that doesn’t use that function call, that’s fine too!

**Comment by ClioCJS** [comment]
Maybe it is. It wasn't as easy to me as doing my android devices. Or even
that old iPhone 2 (original).  I ended up with zJailbreak, Arizhuang,
Electra, Xabsi, Cydia, Taigone all installed, and never really being sure
if I actually did it or not. I guess it is, haha :)
